### ISSUE TITLE
Command artisan view:cache - error - v2

### ISSUE THREAD

**Issue by Felda01** [BRACKETS-by-TRIAD/craftable-pro-docs#85] opened 2024-04-27 13:43 UTC
Hi,

command `php artisan view:cache` returns error: ` The "____path____/vendor/brackets/craftable-pro/src/../resources/views/auth/" directory does not exist.`

`CraftableProServiceProvider@configurePackage` - `$this->loadViewsFrom(__DIR__ . '/../resources/views/auth/', 'brackets/craftable-pro/auth');`

Similar issue: https://github.com/BRACKETS-by-TRIAD/craftable-pro-docs/issues/52

Thanks

**Comment by strstensky** [comment] 2024-09-28 20:45
Duplicate of #52 - solved in version v1.1.21.

**Closed by strstensky** 2024-09-28 20:45 UTC
