### ISSUE TITLE
Unable to crop image

### ISSUE THREAD

**Issue by timoransky** [BRACKETS-by-TRIAD/craftable-pro-docs#53] opened 2023-09-20 07:20 UTC
When uploading an image, after clicking on "Crop" button, I don't see the image in the crop editor:
![image](https://github.com/BRACKETS-by-TRIAD/craftable-pro-docs/assets/15653065/da77a8f0-1bcc-4293-b030-945c95519b05)

**Comment by VladyslavMazurets** [comment] 2023-09-21 13:17
Resolved in PR: [Fix/Unable-To-Crop-Image](https://github.com/BRACKETS-by-TRIAD/craftable-pro/pull/327)

**Comment by blazodragan** [comment] 2023-10-04 09:18
Hi is this fixed I see the same problem still on your demo the problem is there to .

**Comment by timoransky** [comment] 2023-10-04 09:21
Hi @blazodragan ,

It's fixed, but not yet deployed. Since there are other issues waiting to be deployed as well, we will try to get it out by the end of this week.

Thank you for your patience ✌️

**Comment by VladyslavMazurets** [comment] 2023-10-24 14:43
This was fixed in v1.1.21

**Closed by VladyslavMazurets** 2023-10-24 14:43 UTC
